version: '3.8'

services:
  mongo:
    image: mongo:latest   # Uses the latest MongoDB version
    container_name: mongo-db
    ports:
      - "27017:27017"      # Exposes MongoDB default port to the host machine
    volumes:
      - mongo_data:/data/db   # Persists MongoDB data between restarts
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped    # Ensures MongoDB restarts automatically on failure

  mongo-express:
    image: mongo-express:latest    # Mongo-Express image
    container_name: mongo-express
    ports:
      - "8081:8081"      # Exposes Mongo-Express web panel on port 8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo     # Name of the MongoDB service
      - ME_CONFIG_MONGODB_PORT=27017       # MongoDB port
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root  # MongoDB admin username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example  # MongoDB admin password
      - ME_CONFIG_SITE_PORT=8081          # The port the web panel will be available on
    depends_on:
      - mongo  # Wait for MongoDB to start before starting Mongo-Express

volumes:
  mongo_data:  # Named volume for persistent MongoDB data storage
